language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3.0
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-couchbase.gemspec
- gem install sensu-plugins-couchbase-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: E3kw2PPUnj5b0aMjst+4/ctMCSnB1uQE0fFcU8qsj3YaevlN1t2tunMFl58ANX4/cE/KthFQ/rfCYbUTYVURnZ1rfsTaDMamN9bZGmwld7O/0axDEjkC9PQGTfLsoeXSTRnM2erj1s/N9mNHvZgw7l5rhu3GNEsC+jBao60mQCU=
  gem: sensu-plugins-couchbase
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    repo: sensu-plugins/sensu-plugins-couchbase
